config/routes.rb
Rails.application.routes.draw do
  resources :loan_extension_reqs
  resources :loans
  resources :books
  resources :users

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :loan
  has_many :loan_extension_reqs, :through => :loan, :source => :user

  accepts_nested_attributes_for :loan, :allow_destroy => true

  def loaned?
    loan.exists?(:return_date => nil)
  end

  def current_borrower
    if loaned?
      loan.first(:order => "out_date desc").user
    end
  end


  
  def add_loan (username)
  loan.create(:call_no   => id,
                    :username => username,
                    :start_date  => Date.current)
  end
end

app/models/loan.rb
class Loan < ActiveRecord::Base
  belongs_to :book
  belongs_to :user
end

app/models/loan_extension_req.rb
class LoanExtensionReq < ActiveRecord::Base
end

app/models/user.rb
class Person < ActiveRecord::Base
  has_many :loan
  has_many :books, :through => :loans
end

app/controllers/application_controller.1.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

 
  def index
    @books = Book.all
  end

  
  def show
  end

  
  def new
    @book = Book.new
  end

  
  def edit
  end

  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

 
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def loan
  @book.add_loan(params[:book_loan][:person_id])

  redirect_to :action => 'book', :id => params[:id]
  end

  private
  
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:call_no, :title, :authors)
    end
end

app/controllers/loan_extension_reqs_controller.rb
class LoanExtensionReqsController < ApplicationController
  before_action :set_loan_extension_req, only: [:show, :edit, :update, :destroy]

  
  def index
    @loan_extension_reqs = LoanExtensionReq.all
  end

  
  def show
  end

  
  def new
    @loan_extension_req = LoanExtensionReq.new
  end

 
  def edit
  end

  
  def create
    @loan_extension_req = LoanExtensionReq.new(loan_extension_req_params)

    respond_to do |format|
      if @loan_extension_req.save
        format.html { redirect_to @loan_extension_req, notice: 'Loan extension req was successfully created.' }
        format.json { render :show, status: :created, location: @loan_extension_req }
      else
        format.html { render :new }
        format.json { render json: @loan_extension_req.errors, status: :unprocessable_entity }
      end
    end
  end

 
  def update
    respond_to do |format|
      if @loan_extension_req.update(loan_extension_req_params)
        format.html { redirect_to @loan_extension_req, notice: 'Loan extension req was successfully updated.' }
        format.json { render :show, status: :ok, location: @loan_extension_req }
      else
        format.html { render :edit }
        format.json { render json: @loan_extension_req.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def destroy
    @loan_extension_req.destroy
    respond_to do |format|
      format.html { redirect_to loan_extension_reqs_url, notice: 'Loan extension req was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
   
    def set_loan_extension_req
      @loan_extension_req = LoanExtensionReq.find(params[:id])
    end

    
    def loan_extension_req_params
      params.require(:loan_extension_req).permit(:return_date, :status)
    end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: [:show, :edit, :update, :destroy]

  
  def index
    @loans = Loan.all
  end

 
  def show
  end

 
  def new
    @loan = Loan.new
  end

 
  def edit
  end

  
  def create
    @loan = Loan.new(loan_params)

    respond_to do |format|
      if @loan.save
        format.html { redirect_to @loan, notice: 'Loan was successfully created.' }
        format.json { render :show, status: :created, location: @loan }
      else
        format.html { render :new }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def update
    respond_to do |format|
      if @loan.update(loan_params)
        format.html { redirect_to @loan, notice: 'Loan was successfully updated.' }
        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { render :edit }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

 
  def destroy
    @loan.destroy
    respond_to do |format|
      format.html { redirect_to loans_url, notice: 'Loan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    
    def set_loan
      @loan = Loan.find(params[:id])
    end

   
    def loan_params
      params.require(:loan).permit(:start_date, :return_date, :cost)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

 
  def index
    @users = User.all
  end

  
  def show
  end

  
  def new
    @user = User.new
  end

  
  def edit
  end


  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

 
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # This uses callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.......lol
    def user_params
      params.require(:user).permit(:username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/loan_extension_reqs_helper.rb
module LoanExtensionReqsHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :call_no %><br>
    <%= f.text_field :call_no %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :authors %><br>
    <%= f.text_field :authors %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Books</h1>

<table>
  <thead>
    <tr>
      <th>Call no</th>
      <th>Title</th>
      <th>Authors</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.call_no %></td>
        <td><%= book.title %></td>
        <td><%= book.authors %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Call no:</strong>
  <%= @book.call_no %>
</p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Authors:</strong>
  <%= @book.authors %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Library</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/loan_extension_reqs/_form.html.erb
<%= form_for(@loan_extension_req) do |f| %>
  <% if @loan_extension_req.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@loan_extension_req.errors.count, "error") %> prohibited this loan_extension_req from being saved:</h2>

      <ul>
      <% @loan_extension_req.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :return_date %><br>
    <%= f.date_select :return_date %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/loan_extension_reqs/edit.html.erb
<h1>Editing Loan Extension Req</h1>

<%= render 'form' %>

<%= link_to 'Show', @loan_extension_req %> |
<%= link_to 'Back', loan_extension_reqs_path %>

app/views/loan_extension_reqs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Loan Extension Reqs</h1>

<table>
  <thead>
    <tr>
      <th>Return date</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @loan_extension_reqs.each do |loan_extension_req| %>
      <tr>
        <td><%= loan_extension_req.return_date %></td>
        <td><%= loan_extension_req.status %></td>
        <td><%= link_to 'Show', loan_extension_req %></td>
        <td><%= link_to 'Edit', edit_loan_extension_req_path(loan_extension_req) %></td>
        <td><%= link_to 'Destroy', loan_extension_req, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Loan extension req', new_loan_extension_req_path %>

app/views/loan_extension_reqs/new.html.erb
<h1>New Loan Extension Req</h1>

<%= render 'form' %>

<%= link_to 'Back', loan_extension_reqs_path %>

app/views/loan_extension_reqs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Return date:</strong>
  <%= @loan_extension_req.return_date %>
</p>

<p>
  <strong>Status:</strong>
  <%= @loan_extension_req.status %>
</p>

<%= link_to 'Edit', edit_loan_extension_req_path(@loan_extension_req) %> |
<%= link_to 'Back', loan_extension_reqs_path %>

app/views/loans/_form.html.erb
<%= form_for(@loan) do |f| %>
  <% if @loan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@loan.errors.count, "error") %> prohibited this loan from being saved:</h2>

      <ul>
      <% @loan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :return_date %><br>
    <%= f.date_select :return_date %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/loans/edit.html.erb
<h1>Editing Loan</h1>

<%= render 'form' %>

<%= link_to 'Show', @loan %> |
<%= link_to 'Back', loans_path %>

app/views/loans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Loans</h1>

<table>
  <thead>
    <tr>
      <th>Start date</th>
      <th>Return date</th>
      <th>Cost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @loans.each do |loan| %>
      <tr>
        <td><%= loan.start_date %></td>
        <td><%= loan.return_date %></td>
        <td><%= loan.cost %></td>
        <td><%= link_to 'Show', loan %></td>
        <td><%= link_to 'Edit', edit_loan_path(loan) %></td>
        <td><%= link_to 'Destroy', loan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Loan', new_loan_path %>

app/views/loans/new.html.erb
<h1>New Loan</h1>

<%= render 'form' %>

<%= link_to 'Back', loans_path %>

app/views/loans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start date:</strong>
  <%= @loan.start_date %>
</p>

<p>
  <strong>Return date:</strong>
  <%= @loan.return_date %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @loan.cost %>
</p>

<%= link_to 'Edit', edit_loan_path(@loan) %> |
<%= link_to 'Back', loans_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>